### ISSUE TITLE
Backend API Example

### ISSUE THREAD

**Issue by aurexs** [MyraxByte/react-vite-template#1]
Hello.

Is there any example of BackEnd implementation?

Or how can I simulate the responses of Login or /shared/constants.

**Comment by MyraxByte** [comment]
@aurexs Hi, things like shared/constants are needed to get some persistent data for the client from the backend (like a list of countries).

Everything mentioned in the template is an example for realization and you can (should) replace everything for your needs.

For the example, /auth/login should have the following response:
```json
{
  "status": 200,
  "data": {
    "token": "some token",
    "expire": 1704205854 // timestamp token expired
  }
}
```
